### ISSUE TITLE
App crash when starting to record trip

### ISSUE THREAD

**Issue by David-Jackson** [David-Jackson/RoadQuality#26]
@makled1 found a bug that crashes the app on API level 23. Here is the log for the crash:

```
06/25 19:43:43: Launching app
$ adb install-multiple -r -t C:\Users\Makled\Desktop\RoadQuality-master\app\build\intermediates\split-apk\debug\slices\slice_0.apk C:\Users\Makled\Desktop\RoadQuality-master\app\build\intermediates\split-apk\debug\slices\slice_8.apk C:\Users\Makled\Desktop\RoadQuality-master\app\build\intermediates\split-apk\debug\slices\slice_3.apk C:\Users\Makled\Desktop\RoadQuality-master\app\build\intermediates\split-apk\debug\slices\slice_2.apk C:\Users\Makled\Desktop\RoadQuality-master\app\build\intermediates\split-apk\debug\slices\slice_9.apk C:\Users\Makled\Desktop\RoadQuality-master\app\build\intermediates\split-apk\debug\slices\slice_4.apk C:\Users\Makled\Desktop\RoadQuality-master\app\build\intermediates\split-apk\debug\dep\dependencies.apk C:\Users\Makled\Desktop\RoadQuality-master\app\build\intermediates\split-apk\debug\slices\slice_1.apk C:\Users\Makled\Desktop\RoadQuality-master\app\build\intermediates\split-apk\debug\slices\slice_7.apk C:\Users\Makled\Desktop\RoadQuality-master\app\build\intermediates\split-apk\debug\slices\slice_6.apk C:\Users\Makled\Desktop\RoadQuality-master\app\build\intermediates\split-apk\debug\slices\slice_5.apk C:\Users\Makled\Desktop\RoadQuality-master\app\build\intermediates\instant-run-apk\debug\app-debug.apk 
Split APKs installed
$ adb shell am start -n "app.roadquality.roadquality/app.roadquality.roadquality.ActivityMain" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Client not ready yet..Connected to process 10420 on device emulator-5554
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/System: ClassLoader referenced unknown path: /data/app/app.roadquality.roadquality-1/lib/x86
I/FirebaseInitProvider: FirebaseApp initialization unsuccessful
I/InstantRun: starting instant run server: is main process
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
W/Resources: Drawable app.roadquality.roadquality:drawable/avd_play_to_pause_96dp has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).
             java.lang.RuntimeException
                 at android.content.res.Resources.getDrawable(Resources.java:742)
                 at app.roadquality.roadquality.animation.MorphingFab.setAvd(MorphingFab.java:76)
                 at app.roadquality.roadquality.animation.MorphingFab.<init>(MorphingFab.java:40)
                 at app.roadquality.roadquality.ActivityMain$2.<init>(ActivityMain.java:119)
                 at app.roadquality.roadquality.ActivityMain.setupFab(ActivityMain.java:116)
                 at app.roadquality.roadquality.ActivityMain.onCreate(ActivityMain.java:100)
                 at android.app.Activity.performCreate(Activity.java:6662)
                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                 at android.app.ActivityThread.-wrap12(ActivityThread.java)
                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                 at android.os.Handler.dispatchMessage(Handler.java:102)
                 at android.os.Looper.loop(Looper.java:154)
                 at android.app.ActivityThread.main(ActivityThread.java:6077)
                 at java.lang.reflect.Method.invoke(Native Method)
                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
W/Resources: Drawable app.roadquality.roadquality:drawable/avd_pause_to_play_96dp has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).
             java.lang.RuntimeException
                 at android.content.res.Resources.getDrawable(Resources.java:742)
                 at app.roadquality.roadquality.animation.MorphingFab.setAvd(MorphingFab.java:78)
                 at app.roadquality.roadquality.animation.MorphingFab.<init>(MorphingFab.java:40)
                 at app.roadquality.roadquality.ActivityMain$2.<init>(ActivityMain.java:119)
                 at app.roadquality.roadquality.ActivityMain.setupFab(ActivityMain.java:116)
                 at app.roadquality.roadquality.ActivityMain.onCreate(ActivityMain.java:100)
                 at android.app.Activity.performCreate(Activity.java:6662)
                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                 at android.app.ActivityThread.-wrap12(ActivityThread.java)
                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                 at android.os.Handler.dispatchMessage(Handler.java:102)
                 at android.os.Looper.loop(Looper.java:154)
                 at android.app.ActivityThread.main(ActivityThread.java:6077)
                 at java.lang.reflect.Method.invoke(Native Method)
                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
D/: HostConnection::get() New Host Connection established 0x9b9795c0, tid 10420
W/: Unrecognized GLES max version string in extensions: ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 
D/: HostConnection::get() New Host Connection established 0x9b979780, tid 10444
W/: Unrecognized GLES max version string in extensions: ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer: Swap behavior 0
D/EGL_emulation: eglCreateContext: 0x9e438900: maj 2 min 0 rcv 2
D/ActivityMain: onGlobalLayout: FAB SHOULD BE CLOSED ON START
D/EGL_emulation: eglMakeCurrent: 0x9e438900: ver 2 0 (tinfo 0x9e444180)
W/Resources: Drawable app.roadquality.roadquality:drawable/avd_play_to_road_96dp has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).
             java.lang.RuntimeException
                 at android.content.res.Resources.getDrawable(Resources.java:742)
                 at app.roadquality.roadquality.animation.MorphingFab.setAvd(MorphingFab.java:76)
                 at app.roadquality.roadquality.animation.MorphingFab.<init>(MorphingFab.java:40)
                 at app.roadquality.roadquality.ActivityMain$11.<init>(ActivityMain.java:474)
                 at app.roadquality.roadquality.ActivityMain.transitionToIntro(ActivityMain.java:469)
                 at app.roadquality.roadquality.ActivityMain.setupAfterFirstDraw(ActivityMain.java:148)
                 at app.roadquality.roadquality.ActivityMain.access$200(ActivityMain.java:63)
                 at app.roadquality.roadquality.ActivityMain$3.run(ActivityMain.java:138)
                 at android.os.Handler.handleCallback(Handler.java:751)
                 at android.os.Handler.dispatchMessage(Handler.java:95)
                 at android.os.Looper.loop(Looper.java:154)
                 at android.app.ActivityThread.main(ActivityThread.java:6077)
                 at java.lang.reflect.Method.invoke(Native Method)
                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
W/Resources: Drawable app.roadquality.roadquality:drawable/avd_road_animation has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).
             java.lang.RuntimeException
                 at android.content.res.Resources.getDrawable(Resources.java:742)
                 at app.roadquality.roadquality.animation.MorphingFab.setAvd(MorphingFab.java:78)
                 at app.roadquality.roadquality.animation.MorphingFab.<init>(MorphingFab.java:40)
                 at app.roadquality.roadquality.ActivityMain$11.<init>(ActivityMain.java:474)
                 at app.roadquality.roadquality.ActivityMain.transitionToIntro(ActivityMain.java:469)
                 at app.roadquality.roadquality.ActivityMain.setupAfterFirstDraw(ActivityMain.java:148)
                 at app.roadquality.roadquality.ActivityMain.access$200(ActivityMain.java:63)
                 at app.roadquality.roadquality.ActivityMain$3.run(ActivityMain.java:138)
                 at android.os.Handler.handleCallback(Handler.java:751)
                 at android.os.Handler.dispatchMessage(Handler.java:95)
                 at android.os.Looper.loop(Looper.java:154)
                 at android.app.ActivityThread.main(ActivityThread.java:6077)
                 at java.lang.reflect.Method.invoke(Native Method)
                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
I/Choreographer: Skipped 32 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation: eglMakeCurrent: 0x9e438900: ver 2 0 (tinfo 0x9e444180)
I/Choreographer: Skipped 36 frames!  The application may be doing too much work on its main thread.
I/Choreographer: Skipped 32 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation: eglMakeCurrent: 0x9e438900: ver 2 0 (tinfo 0x9e444180)
I/art: Background partial concurrent mark sweep GC freed 1610(193KB) AllocSpace objects, 2(40KB) LOS objects, 39% free, 5MB/8MB, paused 46.624ms total 143.399ms
W/Resources: Drawable app.roadquality.roadquality:drawable/avd_play_to_pause_96dp has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).
             java.lang.RuntimeException
                 at android.content.res.Resources.getDrawable(Resources.java:742)
                 at app.roadquality.roadquality.animation.MorphingFab.setAvd(MorphingFab.java:76)
                 at app.roadquality.roadquality.animation.MorphingFab.<init>(MorphingFab.java:40)
                 at app.roadquality.roadquality.ActivityMain$2.<init>(ActivityMain.java:119)
                 at app.roadquality.roadquality.ActivityMain.setupFab(ActivityMain.java:116)
                 at app.roadquality.roadquality.ActivityMain.onCreate(ActivityMain.java:100)
                 at android.app.Activity.performCreate(Activity.java:6662)
                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                 at android.app.ActivityThread.-wrap12(ActivityThread.java)
                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                 at android.os.Handler.dispatchMessage(Handler.java:102)
                 at android.os.Looper.loop(Looper.java:154)
                 at android.app.ActivityThread.main(ActivityThread.java:6077)
                 at java.lang.reflect.Method.invoke(Native Method)
                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
D/ActivityMain: onGlobalLayout: FAB SHOULD BE CLOSED ON START
I/zzbz: Making Creator dynamically
I/DynamiteModule: Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:220
                  Selected remote version of com.google.android.gms.maps_dynamite, version >= 220
W/System: ClassLoader referenced unknown path: 
I/Google Maps Android API: Google Play services client version: 11910000
I/Google Maps Android API: Google Play services package version: 12685026
E/art: The String#value field is not present on Android versions >= 6.0
I/art: Background sticky concurrent mark sweep GC freed 11535(1769KB) AllocSpace objects, 7(372KB) LOS objects, 25% free, 6MB/8MB, paused 9.450ms total 161.069ms
I/art: Background sticky concurrent mark sweep GC freed 5013(1046KB) AllocSpace objects, 0(0B) LOS objects, 15% free, 7MB/8MB, paused 12.352ms total 101.552ms
I/Choreographer: Skipped 265 frames!  The application may be doing too much work on its main thread.
E/RecyclerView: No adapter attached; skipping layout
D/EGL_emulation: eglMakeCurrent: 0x9e438900: ver 2 0 (tinfo 0x9e444180)
I/Choreographer: Skipped 42 frames!  The application may be doing too much work on its main thread.
D/AnimationManager: onMapReady: Map Ready
D/AnimationManager: run: Timer Expired
D/: HostConnection::get() New Host Connection established 0xa9088940, tid 10535
W/: Unrecognized GLES max version string in extensions: ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 
D/EGL_emulation: eglCreateContext: 0xa9085f60: maj 1 min 0 rcv 1
D/EGL_emulation: eglMakeCurrent: 0xa9085f60: ver 1 0 (tinfo 0xa90835c0)
```

**Comment by David-Jackson** [comment]
This is probably an issue from way the MorphingFab class uses AVDs. d7c22fbf5ce0da334ce42335a369b3416736e1c5 is an attempt to fix this issue.
